---
version: "3.8"
services:
  app1:
    image: alpine:latest
    container_name: app1
    command: sleep 20m
    labels:
      com.example.description: "Accounting webapp"
      com.example.department: "Finance"
      com.example.type: "Application"
  app2:
    image: python:alpine
    container_name: app2
    command: python -m http.server 80 -d /tmp/
    ports:
      - 80:80
    labels:
      com.example.description: "Important Web App"
      com.example.department: "Finance"
      com.example.type: "Application"
  web1:
    image: busybox:latest
    container_name: web1
    command: httpd -p 81 -h /var/www/ -f
    ports:
      - 81:81
    labels:
      com.example.description: "Static web 2"
      com.example.department: "Finance"
      com.example.type: "Content Server"

