---

# - name: Set some facts
#   ansible.builtin.set_fact:
#     test_var: "I'm defined in set_fact"

- name: Include OS vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Debug print from testrole
  ansible.builtin.debug:
    msg: test_var={{ test_var | default("Undefined on the testrole level") }}
