---
- name: Testing
  hosts: localhost
  connection: local
  tasks:
    - name: Do not count this as a failure
      ansible.builtin.command: /usr/bin/true # in Linux: /bin/false
      register: ret_command
      changed_when: ret_command.rc == 0
      failed_when: ret_command.rc == 1

    - name: DEBUG
      ansible.builtin.debug:
        msg: "Test"
      when: ret_command.rc == 0
